#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo ufw allow 1344
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
backend web-backend
        balance roundrobin
        option forwardfor
        server 211831-web-01 100.24.72.11:80 check
        server 211831-web-02 3.95.32.238:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
