#!/usr/bin/env bash
# This script Indefinitely writes I am alive! to the file /tmp/my_process with pause for 2 seconds
while true
do
    sudo bash -c "echo \"I am alive!\" >> /tmp/my_process"
    sleep 2
done
